[build]
  publish = "."  # This sets the root of your project as the publish directory
  functions = "netlify/functions"  # Ensure this points to your functions directory

# Optional: [dev] settings for local development
[dev]
  publish = "."  # Same as above, root directory for static files
  # Add other [dev] settings as needed
